STRCMP:
    ; STR1 = G0
    ; STR2 = G1
STRCMP_LOOP:
    CMP8 [G0], [G1]
    JNE STRCMP_FAIL
    CMP8 [G0], 0
    JE STRCMP_SUCCESS
    ADD64 G0, 1
    ADD64 G1, 1
    JMP STRCMP_LOOP
STRCMP_SUCCESS:
    MOV8 G2, 0
    RET
STRCMP_FAIL:
    MOV8 G2, 1
    RET