IVT_TABLE:
    ; EACH ENTRY IS 9 BYTES LONG (8 BYTES FOR ADDRESS 1 BYTE FOR FLAGS)
    RES8 288 ; 32 ENTRIES

IVT_STRUC:
    D64 IVT_TABLE
    D8 32 ; COUNT

IVT_INIT:
    MOV64 IVTBL, IVT_STRUC
    SEI
    RET

IVT_INSTALL:
    ; VEC = G0
    ; ADDR = G1
    MUL64 G0, 9
    MOV64 [IVT_TABLE+G0], G1
    ADD64 G0, 8
    MOV8 [IVT_TABLE+G0], 1 ; PRESENT FLAG
    RET